bin/setup.py: Avoid errors when upgrade from previous project
Issue: LINUXEXEC-33171

Fixed errors when upgrade from an old project:
ERROR: xml.etree.ElementTree.ParseError: no element found: line 2, column 0

This is because the old style default.xml doesn't end with '/>', check to skip
that kind of lines, and let setup repo --repo-force-sync when needed.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>