bin/logger_setup.py: use buffered mechanism to avoid crazy output format
It's hard to predict how programs will output things, and using logger
to output every single message will introduce crazy output.

For example, if a program first prints 'Execption', then ':', the result
is normally 'Exception:' on the screen, but with logger, the result will
be:
"""
Exception
:
"""

The above behavior is actually what python 3.12 prints its calltrace.
We thus need to introduce a buffered mechanism to get rid of such crazy
output.

Issue: LIN1024-3073

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>

After apply the commit:
```
$ wrlinux-x/setup.sh --distro=wrlinux-graphics --machines=intel-x86-64 --dl-layers --all-layers
...
CRITICAL: cmd "bin/git-repo/repo init --no-clone-bundle -m default.xml -u . --no-repo-verify --repo-url bin/git-repo --repo-branch abc --quiet" returned 1
ERROR: Traceback (most recent call last):
ERROR:   File "wrlinux-x/bin/setup.py", line 2115, in <module>
ERROR:     x.main(sys.argv)
ERROR:   File "wrlinux-x/bin/setup.py", line 331, in main
ERROR:     self.repo_sync()
ERROR:   File "wrlinux-x/bin/setup.py", line 1677, in repo_sync
ERROR:     self.call_repo_init()
ERROR:   File "wrlinux-x/bin/setup.py", line 1904, in call_repo_init
ERROR:     utils_setup.run_cmd(cmd, environment=self.env, log=log_it)
ERROR:   File "wrlinux-x/bin/utils_setup.py", line 76, in run_cmd
ERROR:     raise Exception(msg)
ERROR: Exception
```

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>